"""Database creation

Revision ID: bd393b9446b2
Revises: 
Create Date: 2023-07-29 23:52:10.556013

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd393b9446b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_index('ix_boss_of_apps_id', table_name='boss_of_apps')
    op.drop_table('boss_of_apps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_of_apps',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='boss_of_apps_pkey')
                    )
    op.create_index('ix_boss_of_apps_id', 'boss_of_apps', ['id'], unique=False)
    op.drop_table('windows')
    # ### end Alembic commands ###
