"""Upgrade tables

Revision ID: bdac4783d21f
Revises: bd393b9446b2
Create Date: 2023-07-30 12:45:52.138321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdac4783d21f'
down_revision = 'bd393b9446b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('windows', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'windows', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'windows', type_='foreignkey')
    op.drop_column('windows', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
